- src/main/java/embl/ebi/variation/eva/vcfdump/VariantExporter.java
VCFDumper: added GT format line to the header if not present in the sources (EVA-413)
> EVA-413 VCFDumper: added GT format line to the header 

- vcf-dumper/vcf-dumper-lib/src/main/java/uk/ac/ebi/eva/vcfdump/VariantExporter.java
- vcf-dumper/vcf-dumper-lib/src/main/java/uk/ac/ebi/eva/vcfdump/VcfHeaderFilteringLineIterator.java
- vcf-dumper/vcf-dumper-lib/src/test/java/uk/ac/ebi/eva/vcfdump/VariantExporterTest.java
- vcf-dumper/vcf-dumper-lib/src/test/java/uk/ac/ebi/eva/vcfdump/VcfHeaderFilteringLineIteratorTest.java
- vcf-dumper/vcf-dumper-lib/src/test/resources/vcfTestHeader.vcf
If we dump variants from several studies, the headers for those studies are merged. In some cases, there are INFO fields with not compatible values in different studies. Those fields cannot be merged, and the HTSJDK VCF Header merger class throws an exception. 
To solve this issue, we have developed a VCF Header iterator that can filter out field types from the header (like INFO). By default, we will exclude the INFO fields, because they are not being written in the output VCF.
> EVA-496 Filter INFO fields when merging headers

- database-migration/src/main/java/uk/ac/ebi/eva/dbmigration/mongodb/ExtractAnnotationFromVariant.java
- database-migration/src/test/java/uk/ac/ebi/eva/dbmigration/mongodb/ExtractAnnotationFromVariantTest.java
Add a migration changeset that adds a "is_default" flag to every document in annotationMetadata, and set only one to "true". which version is set as default is the same that is added in the other steps, i.e. the attributes `vep.version=78` and `vep.cache.version=78`
> EVA-795 Add default annotation version to database collection

- dbsnp-importer/pom.xml
- dbsnp-importer/src/main/java/uk/ac/ebi/eva/dbsnpimporter/io/readers/SubSnpCoreFieldsReader.java
- dbsnp-importer/src/main/resources/application.properties
- dbsnp-importer/src/test/resources/application.properties
- dbsnp-importer/src/test/resources/data.sql
- dbsnp-importer/src/test/resources/schema.sql
The table `obsvariation` belongs to a different schema than the rest of those queried by the import pipeline. This is now reflected in the code and the test data.
The testing database is composed of 2 schema:
* Organism data in PUBLIC schema (HSQLDB default)
* dbsnp_shared schema for `obsvariation` table
For the production environment, an example properties has been added, with an example of how to configure the organism schema in PostgreSQL. The shared schema is always made explicit in the queries.
> EVA-926 Query the obsvariation table from the shared schema

- dbsnp-importer/src/main/java/uk/ac/ebi/eva/dbsnpimporter/io/readers/SampleReader.java
- dbsnp-importer/src/main/java/uk/ac/ebi/eva/dbsnpimporter/io/readers/SubSnpCoreFieldsReader.java
- dbsnp-importer/src/test/java/uk/ac/ebi/eva/dbsnpimporter/io/readers/SampleReaderTest.java
- dbsnp-importer/src/test/java/uk/ac/ebi/eva/dbsnpimporter/io/readers/SubSnpCoreFieldsReaderTest.java
The names of some of the tables queried for variants depend on the dbSNP build number. For instance, `b150_snpcontigloc` belongs to build 150 and `b140_snpcontigloc` to build 140.
This has been added as a parameter for the variants reader, following the same structure that was already implemented for the samples search.
> EVA-930 Restrict variant search to a specific build

- dbsnp-importer/src/main/java/uk/ac/ebi/eva/dbsnpimporter/configuration/VariantsProcessorConfiguration.java
- dbsnp-importer/src/main/java/uk/ac/ebi/eva/dbsnpimporter/jobs/steps/processors/UnambiguousAllelesFilterProcessor.java
- dbsnp-importer/src/test/java/uk/ac/ebi/eva/dbsnpimporter/jobs/steps/processors/UnambiguousAllelesFilterProcessorTest.java
Variants with IUPAC ambiguity codes either in the reference or alternates alleles must be filtered out. A new processor has been implemented and added to the composite processor.
> EVA-888 Filter out variants with IUPAC codes in allele strings

- dbsnp-importer/src/main/java/uk/ac/ebi/eva/dbsnpimporter/jobs/steps/processors/SubSnpCoreFieldsToEvaSubmittedVariantProcessor.java
- dbsnp-importer/src/test/java/uk/ac/ebi/eva/dbsnpimporter/configuration/ImportVariantsStepConfigurationTest.java
- dbsnp-importer/src/test/java/uk/ac/ebi/eva/dbsnpimporter/jobs/steps/processors/SubSnpCoreFieldsToEvaSubmittedVariantProcessorTest.java
- dbsnp-importer/src/test/java/uk/ac/ebi/eva/dbsnpimporter/jobs/steps/processors/SubSnpCoreFieldsToVariantProcessorTest.java
Update the importer with the changes in variation commons about the dbsnpIds. 
Travis will fail until https://github.com/EBIvariation/variation-commons/pull/59 is merged and deployed.
> EVA-971 Retain submitted identifiers in VCFs

- dbsnp-importer/src/main/java/uk/ac/ebi/eva/dbsnpimporter/configuration/VariantsProcessorConfiguration.java
- dbsnp-importer/src/main/java/uk/ac/ebi/eva/dbsnpimporter/jobs/steps/processors/MissingCoordinatesFilterProcessor.java
- dbsnp-importer/src/main/java/uk/ac/ebi/eva/dbsnpimporter/models/SubSnpCoreFields.java
- dbsnp-importer/src/test/java/uk/ac/ebi/eva/dbsnpimporter/jobs/steps/processors/MissingCoordinatesFilterProcessorTest.java
- dbsnp-importer/src/test/java/uk/ac/ebi/eva/dbsnpimporter/models/SubSnpCoreFieldsTest.java
Implemented new processor that filters out variants without reported coordinates. This check was previously implemented in the `SubSnpCoreFields` constructor but that wasn't correct because the "legacy" accession tracker should accept those.
> EVA-974 Filter out variants with no contig or chromosome coordinates

- dbsnp-importer/src/main/java/uk/ac/ebi/eva/dbsnpimporter/io/readers/SubSnpCoreFieldsReader.java
Ordering query results by RefSNP ID halves the time required to execute the variant import.
> EVA-946 Ordering query results by RefSNP instead of SubSNP ID

- dbsnp-importer/src/main/java/uk/ac/ebi/eva/dbsnpimporter/parameters/Parameters.java
For spring to put properties in our `@ConfigurationProperties` beans, the beans need setters.
without this, the job fails because the path to the mapping file is null.
> EVA-431 Read contig aliases: bugfix

- dbsnp-importer/src/main/java/uk/ac/ebi/eva/dbsnpimporter/configuration/ImportVariantsStepConfiguration.java
- dbsnp-importer/src/main/java/uk/ac/ebi/eva/dbsnpimporter/configuration/ListenersConfiguration.java
- dbsnp-importer/src/main/java/uk/ac/ebi/eva/dbsnpimporter/contig/RefseqAssemblyReportParser.java
- dbsnp-importer/src/main/java/uk/ac/ebi/eva/dbsnpimporter/jobs/steps/processors/MatchingAllelesFilterProcessor.java
- dbsnp-importer/src/main/java/uk/ac/ebi/eva/dbsnpimporter/jobs/steps/processors/MissingCoordinatesFilterProcessor.java
- dbsnp-importer/src/main/java/uk/ac/ebi/eva/dbsnpimporter/jobs/steps/processors/UnambiguousAllelesFilterProcessor.java
- dbsnp-importer/src/main/java/uk/ac/ebi/eva/dbsnpimporter/models/SubSnpCoreFields.java
Add more logging to see where exactly are the delays, whether it's before, during or after receiving the elements in the reader part of the step.
I'm using a manual count because the readCount in the stepExecution is not updated within a batch.
> EVA-1015 Improve logging to show times around the query

- dbsnp-importer/src/main/java/uk/ac/ebi/eva/dbsnpimporter/io/readers/SubSnpCoreFieldsReader.java
- dbsnp-importer/src/main/java/uk/ac/ebi/eva/dbsnpimporter/io/readers/SubSnpCoreFieldsRowMapper.java
- dbsnp-importer/src/main/java/uk/ac/ebi/eva/dbsnpimporter/jobs/steps/processors/SubSnpCoreFieldsToVariantProcessor.java
- dbsnp-importer/src/main/java/uk/ac/ebi/eva/dbsnpimporter/models/SubSnpCoreFields.java
- dbsnp-importer/src/test/java/uk/ac/ebi/eva/dbsnpimporter/io/readers/SubSnpCoreFieldsReaderTest.java
- dbsnp-importer/src/test/java/uk/ac/ebi/eva/dbsnpimporter/jobs/steps/processors/MatchingAllelesFilterProcessorTest.java
- dbsnp-importer/src/test/java/uk/ac/ebi/eva/dbsnpimporter/jobs/steps/processors/MissingCoordinatesFilterProcessorTest.java
- dbsnp-importer/src/test/java/uk/ac/ebi/eva/dbsnpimporter/jobs/steps/processors/RefseqToGenbankMappingProcessorTest.java
- dbsnp-importer/src/test/java/uk/ac/ebi/eva/dbsnpimporter/jobs/steps/processors/SubSnpCoreFieldsToEvaSubmittedVariantProcessorTest.java
- dbsnp-importer/src/test/java/uk/ac/ebi/eva/dbsnpimporter/jobs/steps/processors/SubSnpCoreFieldsToVariantProcessorTest.java
- dbsnp-importer/src/test/java/uk/ac/ebi/eva/dbsnpimporter/jobs/steps/processors/UnambiguousAllelesFilterProcessorTest.java
- dbsnp-importer/src/test/java/uk/ac/ebi/eva/dbsnpimporter/models/SubSnpCoreFieldsForwardStrandMappingTest.java
- dbsnp-importer/src/test/java/uk/ac/ebi/eva/dbsnpimporter/models/SubSnpCoreFieldsGetVariantCoordinatesTest.java
- dbsnp-importer/src/test/java/uk/ac/ebi/eva/dbsnpimporter/models/SubSnpCoreFieldsGetVariantCoreFieldsTest.java
- dbsnp-importer/src/test/java/uk/ac/ebi/eva/dbsnpimporter/models/SubSnpCoreFieldsTest.java
SubSNPCoreFieldReader.java - Included genotype field
SubSNPCoreFields.java - Included genotype field and updated equals/hashcode methods to accomodate this field
SubSnpCoreFieldsToVariantProcessor.java - Add the genotype list as part of the VariantSourceEntry object
> EVA-883 - Read genotypes for an SS and map to EVA model

- dbsnp-importer/src/main/java/uk/ac/ebi/eva/dbsnpimporter/configuration/ListenersConfiguration.java
The `afterWrite` listener method throws an exception if no items were written, because it tries to access index -1. This is unusual, but it can happen for example if all the variants in a chunk belong to the same contig and that can't be found in the FASTA sequence.
> Avoided exception in 'afterWrite' listener method

- dbsnp-importer/src/main/java/uk/ac/ebi/eva/dbsnpimporter/configuration/SampleReaderConfiguration.java
- dbsnp-importer/src/main/java/uk/ac/ebi/eva/dbsnpimporter/io/readers/SampleReader.java
- dbsnp-importer/src/test/java/uk/ac/ebi/eva/dbsnpimporter/io/readers/SampleReaderTest.java
- dbsnp-importer/src/test/java/uk/ac/ebi/eva/dbsnpimporter/io/readers/WindingItemReaderTest.java
The number of samples in `VariantSource` and `VariantSourceEntry` objects must match.
Because dbSNP don't store missing genotypes, the list of samples retrieved for a given ss ID could be smaller than the total number of those in the batch. When the genotypes are populated in the `variants` collection, this mismatch causes the web services to break.
This PR removes the query on a specific ss ID from the batch to solve the issue.
> Store all samples from a batch

- vcf-dumper/vcf-dumper-lib/pom.xml
We had an issue with plain `mvn clean install` compilations. I tracked down the error to the spring-boot-maven-plugin used in vcf-dumper-lib.
IMO that plugin would only be useful in vcf-dumper-ws.
As a side note, I thought at the beginning that this was caused by overwriting the package uk.ac.ebi.eva.vcfdump in several modules, which turned out irrelevant. I didn't do the refactoring for that in this PR, but it would be cleaner if we did it as well at some point.
> EVA-1113 VCF dumper staging deployment

- vcf-dumper/vcf-dumper-lib/src/main/java/uk/ac/ebi/eva/vcfdump/VariantToVariantContextConverter.java
2 bugs:
- VariantContextBuilder was reusing state across built objects. changing the read preference changes the order of the results, which changes the reused state. Once the state is not reused, the order doesn't matter.
- when a context base is added, the annotation was lost
> EVA-1549 Test APIs and pipelines using RedHat-supported JDK 8 - bug: annotation depends on read preference

- evapro-refresh/evapro_prod_refresh.py
I observed that "\d" does not seem to work in Python 3.8 (dev was done in Python 3.9) in the production deployment in Codon
> EVA-2823 - Use enumerated character class to make regular expression work with Python3.8

- variant-remapping-automation/remapping_automation.py
- variant-remapping-automation/remapping_process.nf
Also few other fixes to the automation, to ensure that clustering is executed on the specified instance and log files don't get overwritten when multiple source assemblies are remapped to a single target.
> EVA-2962 - Add clustering QC job to remapping automation

- variant-remapping-automation/get_custom_assembly.py
Happy to discuss this but considering it caused a lot of failure I'm wondering if crashing when the renaming failed is the best idea.
> EVA-2988 - Make custom assembly renaming optional

- .gitignore
- slurm-scripts/eva-sbatch
- slurm-scripts/eva-srun
See example usage in tasks folder...
I'm not sure it really needs to be this flexible (or in bash), since at a certain point you'd just use sbatch directly... oh well, I was having fun.
> EVA-3575 - sbatch wrapper script

- accession-monitoring/__init__.py
- accession-monitoring/monitor_duplicate_accessions.py
See documentation [here](https://www.mongodb.com/docs/manual/tutorial/connection-pool-performance-tuning/) and specific to mongoexport (which uses the Go driver) [here](https://www.mongodb.com/docs/drivers/go/current/fundamentals/connections/connection-guide/#std-label-golang-connection-options).
I also removed the logging of the export command, as it shows the password in cleartext. It's convenient for debugging but for security reasons I think we'd better do without.
> EVA-3689: Increase connectTimeoutMS for mongoexport

- accession-monitoring/monitor_duplicate_clustering_accessions.nf
Automation to monitor RS duplicate accession
> EVA-3737 - Monitor rs accessions
